services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      ALLOWED_HOSTS: "localhost,127.0.0.1,0.0.0.0"
      TIME_ZONE: "Europe/Prague"
      DB_NAME: "/app/data/db.sqlite3"
      SEED_DEMO_DATA: "1"
    volumes:
      - db_data:/app/data

volumes:
  db_data:
