# Generated by Django 6.0.8 on 2026-09-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
