# Generated by Django 6.0.8 on 2026-09-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_shift_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
