# Generated by Django 5.2.10 on 2026-03-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_shift_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeunavailability',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='ShiftTemplate',
        ),
    ]
